name: twitter_sentiment_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - nltk=3.7
  - pandas=1.2.4
  - pip=22.2.2
  - pip:
      - boto3==1.26.74
      - fsspec==2023.1.0
      - ipykernel==6.16.0
      - langdetect==1.0.9
      - lightgbm==3.3.5
      - matplotlib==3.7.1
      - pyarrow==11.0.0
      - pydantic==1.10.5
      - pytest==7.2.1
      - s3fs==0.4.2
      - scikit-learn==1.2.1
      - streamlit==1.23.1
      - tqdm==4.64.1
      - tweepy==4.4.0