########## Information for Feature Generation ##########
data_keys_dict:
  sentiment140:
    path_proc: !paths sentiment140_path_proc
    path_tfidf: !paths sentiment140_path_tfidf
    text_col_proc: "text_processed"
  covid:
    fpath_proc: !paths covid_fpath_proc
    fpath_tfidf: !paths covid_fpath_tfidf
    file_prefix: "covid"
    text_col_proc: "text_processed"
  congress:
    fpath_proc: !paths congress_fpath_proc
    fpath_tfidf: !paths congress_fpath_tfidf
    file_prefix: "congress"
    text_col_proc: "text_processed"
  twitter:
    fpath_proc: !paths twitter_fpath_proc
    fpath_tfidf: !paths twitter_fpath_tfidf
    file_prefix: "twitter"
    text_col_proc: "text_processed"
  bitcoin:
    fpath_proc: !paths bitcoin_fpath_proc
    fpath_tfidf: !paths bitcoin_fpath_tfidf
    file_prefix: "bitcoin"
    text_col_proc: "text_processed"
  artificial_intelligence:
    fpath_proc: !paths artificial_intelligence_fpath_proc
    fpath_tfidf: !paths artificial_intelligence_fpath_tfidf
    file_prefix: "artificial_intelligence"
    text_col_proc: "text_processed"
  
vectorizer_kwargs:
  max_df: 0.7